### ISSUE TITLE
HDL source available?

### ISSUE THREAD

**Issue by Elgox2** [mathworks/Petalinux#1]
Hello,

I am working with Matlab HDL coder and a custom board, and I would like to use this project as a base to generate the petalinux project for my board. 

Since I need to create a new hdf for my board, I would like to see the original HDL project used to create the included hdf file. I was looking for it in the Matlab help, but it seems that ZCU111 is still not supported there. 

Is it possible to obtain the HDL project (or at least the block diagram tcl script) used here?

**Comment by darenlee** [comment]
Apologies for the late reply. If you still require HDL project source code please contact support@mathworks.com and we can work with you further on this.
